### ISSUE TITLE
chore: Add a GitHub Actions hook to auto upload on Toolforge

### ISSUE THREAD

**Issue by lubianat** [lubianat/inat2wiki-dev#2]
https://github.com/wikimediabrasil/quickstatements3

https://github.com/wikimediabrasil/quickstatements3/blob/main/.github/workflows/toolforge-deploy.yml

in particular

```
name: Toolforge Deploy
on:
  push:
    branches: [ "main" ]
    paths:
      - "uwsgi.ini"
      - "src/**"

jobs:
  deploy:
    name: Deploy to Toolforge
    runs-on: ubuntu-latest

    steps:
      - name: Configure SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Run deployment commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          request_pty: true
          script: |
            set -xe
            become qs-dev git -C '$HOME/www/python' fetch origin
            become qs-dev git -C '$HOME/www/python' reset --hard origin/main
            become qs-dev git -C '$HOME/www/python' pull origin main
            become qs-dev kubectl delete pods -n tool-qs-dev -l app.kubernetes.io/component=webservice-interactive
            become qs-dev webservice --mem 512Mi python3.11 shell -- webservice-python-bootstrap
            become qs-dev webservice --mem 512Mi python3.11 shell -- '$HOME/www/python/venv/bin/python' '$HOME/www/python/src/manage.py' migrate
            become qs-dev webservice --mem 512Mi python3.11 shell -- '$HOME/www/python/venv/bin/python' '$HOME/www/python/src/manage.py' collectstatic --noinput
            become qs-dev webservice python3.11 restart --mem 4Gi
            become qs-dev webservice python3.11 status
```
